apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment1
spec: 
  replicas: 2
  selector:
    matchLabels:
      type: ui-pod
  template:
    metadata:
      labels:
        type: ui-pod
    spec:
      containers:
       - name: con1
         image: aksacr.azurecr.io/todo-ui-micro:v1
         ports:
          - containerPort: 80
         

        

        

  